syslog-ng: add liburing dependency if KERNEL_IO_URING is selected
On OpenWrt buildbots, I noticed that syslog-ng fails for aarch64 and x86_64,
because these two targets has enabled KERNEL_IO_URING [1] and
syslog-ng detects it, wants to use it and thus it fails on buildbots:
In file included from iv_private.h:35,
                 from iv_event.c:27:
iv_private_posix.h:110:49: error: field 'ring' has incomplete type
  110 |                         struct io_uring         ring;
      |                                                 ^~~~
iv_private_posix.h:113:57: error: field 'ts' has incomplete type
  113 |                         struct __kernel_timespec        ts;
      |                                                         ^~
make[9]: *** [Makefile:575: iv_event.lo] Error 1

[1] https://github.com/openwrt/openwrt/blob/0147d213ffaf52a444bf0dd0c2ccd9b929ef448c/config/Config-kernel.in#L571

Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>